### PR TITLE
Add Travis building and uploading of the package

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
Now Travis CI will automatically build the package and when tagged, they
will be automatically uploaded to Bintray.

* beaver ()...v0.1.1(2c6caef) (1 commits)
  > Bugfix: Change TRAVIS_SLUG to TRAVIS_REPO_SLUG

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Red :-)

**Comment by leandro-lucarella-sociomantic** [comment]
Yup, copy&paste error passing stuff in the `Dockerfile` to the script. Updated.

**Comment by leandro-lucarella-sociomantic** [comment]
:green_heart:

**Comment by leandro-lucarella-sociomantic** [comment]
I think I release v0.11.1 after this is merged.

**Comment by nemanja-boric-sociomantic** [comment]
So we got PR testing for free, eh?

**Review by nemanja-boric-sociomantic — APPROVED** [review]
LGTM

**Comment by leandro-lucarella-sociomantic** [comment]
> So we got PR testing for free, eh?

Yeah... "testing".

**Pull request merged**
