### PR TITLE
clone: Make --triangular the default

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
This was announced a long time ago so it's time to make the step forward
(before hitting v1.0.0).

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
ping

**Comment by nemanja-boric-sociomantic** [comment]
Sorry, I've missed this!

**Comment by mihails-strasuns-sociomantic** [comment]
I have missed that old announcement completely. Is it too late to object? :( I don't want to ever use `--trangular`.

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, I'm not sure about consequences of this decision, reading the README.

**Comment by leandro-lucarella-sociomantic** [comment]
> I have missed that old announcement completely. Is it too late to object? :( I don't want to ever use --trangular.

It's just a change of default, if you don't like it just do a `git config --global hub.triangular false` and continue with your miserable life :trollface:

**Comment by leandro-lucarella-sociomantic** [comment]
I don't understand why do you have complains with the triangular workflow. It's MUCH safer than the current default. Could you please give a ground to your concerns?

**Comment by leandro-lucarella-sociomantic** [comment]
This got automatically closed when I removed the master branch :unamused: 

Re-created as #216.

**Pull request closed without merging**
