### PR TITLE
 PEP8 refactoring, bug #98

### PR DESCRIPTION
**Pull request by FedericoCeratto**
PEP8 refactoring, new makefile targets added. Related to #98

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Some comments:

* Needs rebase

* Please don't include the `lint` command if you are not going to fix the warnings and/or use special command-lines arguments to avoid spurious warnings. It makes no sense to have a command spitting ~300 warnings.

* pep8 is still giving errors to me:

  ```
  git-hub:901:40: E225 missing whitespace around operator
  git-hub:907:80: E501 line too long (80 characters)
  ```

* Please remove all formatting changes that are not strictly to comply with PEP8. Formatting is a matter of taste, and since I'm the maintainer of this package, I think I deserve to get to choose the formatting, after all I'm the one that spends the most time looking at and dealing with this code :)

  For example, please don't add extra newlines to put one argument per line when declaring or calling functions, don't align statements broken in more than one lines to the opening parenthesis, just always use one or two "tabs"/4 spaces depending on whatever makes sense):

  ```python
      # NO
      die("Can't find '{}' config key in git config. "
          "Read the man page for details.",
          name)
      # YES
      die("Can't find '{}' config key in git config. "
              "Read the man page for details.", name)

      # NO
      req.add_header("Authorization", "bearer " +
                     self.oauthtoken)
      # YES
      req.add_header("Authorization", "bearer " +
              self.oauthtoken)

      # NO
      group.add_argument(
            '--global',
            dest='opts',
            action='store_const',
            const=['--global'],
            help="store settings in the global configuration "
            "(see git config --global for details)")
      # YES (in this case I use very particular rules, I
      # try to group related arguments together in the
      # same line, and leave the help string in its own line)
      group.add_argument('--global', dest='opts',
          action='store_const', const=['--global'],
          help="store settings in the global configuration "
          "(see git config --global for details)")
   ```

So it would be probably easier to do the re-formatting by just doing a `sed -i 's/\t/    /g git-hub` and do manual changes from there rather than doing a completely re-format of the file, as it looks like you did.

I'm sorry if I'm being too picky, but as I said before, I'm quite comfortable with the current formatting. I'm willing to accept a patch to comply with PEP8 (and fix important pylint issues for that matter) but only if it just makes the minimum amount of changes to the current format to pass the pep8 command.

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, crap. I'm using pep8 from Ubuntu Precise, I updated it and noticed the extra newlines are reported and part of the PEP8. I'm sorry but I'm not willing to comply with that. I find excessive vertical space usage to be very harmful for readability (in the case of the `git_config()` functions it increases the length of the function by 33%, which makes less code fit my screen and thus making harder to read the whole file). Same for extra indentation just to match the opening parenthesis, it makes the code to take more lines due to the extra horizontal space wasted per line.

PEP8 has a whole section about this: "A Foolish Consistency is the Hobgoblin of Little Minds", saying readability matters the most. "Practicality beats Purity". I'm sorry but I will use that for my get-out-of-jail card.

I'm willing to change tabs for spaces for example, and other minor whitespaces changes, but I'm not willing to accept those vertical-space-exploding changes, even if they are in PEP8.

**Comment by leandro-lucarella-sociomantic** [comment]
Good news is you can `--ignore` any rule you want with `pep8`. I still wonder if all this trouble is worthy.

**Comment by leandro-lucarella-sociomantic** [comment]
Closing because of the lack of activity. Feel free to reopen if you are willing to update the PR with the conditions above.

**Comment by maxyz** [comment]
The continuation lines are also defined in pep8 (https://www.python.org/dev/peps/pep-0008/#id1).
And frankly:
```python
group.add_argument('--global', dest='opts',
    action='store_const', const=['--global'],
    help="store settings in the global configuration "
    "(see git config --global for details)")
```
Looks broken.

A pep8 complaint alternative is:
```python
group.add_argument(
    '--global', dest='opts',
    action='store_const', const=['--global'],
    help="store settings in the global configuration "
    "(see git config --global for details)")
```
I guess that's the best of both worlds. (Packing related arguments, keep the indentation fix to the level not to the location of the last `(`, keep continuation lines at their corresponding indentation level).
This takes at most an extra 33% of vertical space (in the worst case).

The extreme version would be:
```python
group.add_argument(
    '--global', dest='opts',
    action='store_const', const=['--global'],
    help=(
        "store settings in the global configuration "
        "(see git config --global for details)"
    ),
)
```
to get even the help strings aligned.

On the other hand, we could minimize the vertical space using the optional extended horizontal limit (100):
```python
group.add_argument(
    '--global', dest='opts', action='store_const', const=['--global'],
    help="store settings in the global configuration (see git config --global for details)")
```

**Comment by leandro-lucarella-sociomantic** [comment]
> I guess that's the best of both worlds.

Yeah, LGTM. I like this one.

**Pull request closed without merging**
