### PR TITLE
rebase: Push rebased commits also to the PR branch

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
This way the commits will be linked to the PR by GitHub.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
FYI @mathias-lang-sociomantic

**Comment by mathias-lang-sociomantic** [comment]
Did you give it a try ? :P

**Comment by leandro-lucarella-sociomantic** [comment]
Nope, I was hoping for your eagerness to take care of that :D

**Comment by nemanja-boric-sociomantic** [comment]
Should we then disable `-D`?

**Comment by leandro-lucarella-sociomantic** [comment]
Why?

**Comment by nemanja-boric-sociomantic** [comment]
Maybe I don't get it. But you push to PR branch that you'll later delete with `-D`?

**Comment by leandro-lucarella-sociomantic** [comment]
In a local test it seems to work now that I reversed the order (first push to the PR branch, then push to the base branch). I'll test `-D` now, but my guess is it should  work.

**Comment by leandro-lucarella-sociomantic** [comment]
> Maybe I don't get it. But you push to PR branch that you'll later delete with -D?

Yes, I think GitHub registers the *events* to track how the PR evolved, so it would be the same as Merging the PR in the web using the Merge/Rebase button and then clicking on the Delete Branch button.

**Comment by nemanja-boric-sociomantic** [comment]
Ah, ok then.

**Comment by leandro-lucarella-sociomantic** [comment]
Yup, it works to remove the branch too :tada:

**Comment by nemanja-boric-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 0d5adfac3c5d7df63315c4788c63d868b11c558a, new (rebased) HEAD is aac3d985db40a39b457a9e4dbe280c52d4f9d2f1

**Comment by gkotian** [comment]
Ah.. I was hoping you would use the changes in this PR when rebasing this PR, so we could verify whether GitHub really managed to link the commit to this PR :)

**Comment by nemanja-boric-sociomantic** [comment]
I already pressed enter before that came to my mind :-)

**Comment by gkotian** [comment]
No worries, but have you guys verified whether GitHub manages to link to PRs as expected? If so, I would request a new `git-hub` release so that we could use this feature in our repos right away.

**Comment by nemanja-boric-sociomantic** [comment]
I thought the fact that this works was implied by @leandro-lucarella-sociomantic's last two comments?

**Comment by mathias-lang-sociomantic** [comment]
It works, I tested it in my fork: https://github.com/mathias-lang-sociomantic/dmd-dlang/commit/2c2895c946bea354d964af5b665b6cc8c4972654

**Comment by leandro-lucarella-sociomantic** [comment]
> No worries, but have you guys verified whether GitHub manages to link to PRs as expected? If so, I would request a new git-hub release so that we could use this feature in our repos right away.

I think I would like for a few more things to get in before releasing v1.0.0, but I could release an alpha, or maybe just release v0.11.

**Pull request closed without merging**
