### PR TITLE
Update to beaver/cachalot and remove trusty support

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
```
* beaver v0.2.1(570562d)...v0.2.2(480e6f5) (3 commits)
  > gen-dockerfile: Fix docker repository and tag parsing
  > editorconfig: Fix indent for Makefiles
  > Mention wildcard support in README
```

### CODE REVIEW

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Comment by mihails-strasuns-sociomantic** [comment]
Typo "remove travis support" :D

**Comment by leandro-lucarella-sociomantic** [comment]
Fixed typo.

**Comment by leandro-lucarella-sociomantic** [comment]
:red_circle: because d-apt repo seems to be down... :unamused:

**Comment by klaus993** [comment]
Asd

**Comment by mihails-strasuns-sociomantic** [comment]
Green now

**Pull request merged**
