### PR TITLE
clone: Make --triangular the default

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
This was announced a long time ago so it's time to make the step forward (before hitting v1.0.0).

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
re: https://github.com/sociomantic-tsunami/git-hub/pull/212#issuecomment-301045826

I object it because the way it is implemented in git-hub, it introduces new remote names which does not interact well with muscle memory. Of course I can configure the option to be disabled globally (and will definitely do) but if I forget, my next `git push -f origin mybranch` will do some nasty things. This is bad.

If git hub would use same `origin`/`upstream` remotes than I would be fine with switching the default as it wouldn't affect semantics of commands I use and become useless but also harmless change.

**Comment by mihails-strasuns-sociomantic** [comment]
As for this:

> It's MUCH safer than the current default

My history of failures with git has taught me that only safe way to play with it is to be as explicit as possible. To never ever use plain `git pull` / `git push` command - specifying remotes and branches for all commands explicitly. With that, triangular workflow does not improve anything.

**Comment by mathias-lang-sociomantic** [comment]
I must say, from what I read, I am not a fan of the triangular workflow as well. Having `origin` as upstream is a recipe for disaster for people with write access. What's the advantage of having triangular ? To me it sounds like trading safety for convenience, something I'm not comfortable with.

**Comment by gavin-norman-sociomantic** [comment]
Wait, what? `origin` is upstream? That does indeed sound weird / dangerous.

**Comment by mihails-strasuns-sociomantic** [comment]
Yep, currently it introduces remotes with names `origin` and `fork`.

**Comment by leandro-lucarella-sociomantic** [comment]
The problem is you got used to working around the lack of a proper suppport for the triangular workflow. Your minds are rotten now :)

If you don't want to use an implicit `pull` or `push` then fine, you are completely unaffected by this, so I don't understand why are you concerned about this change at all.

If you are concerned about the change from `origin` to be upstream now, then we might introduce a new config to change the names to make it less confusing for people used to the old scheme.

Seriously, the triangular workflow is MUCH safer, it configures git to **never push** to the blessed repo implicitly, with the current approach if you accidentally make a `git push` it will push to the blessed repo!!! This is insane.

The blessed repo **should** be *origin*, that's your origin. The fact that the tool called *origin* the fork was a poor choice from the time when git didn't support the triangular workflow.

I have the people that you are against it because you don't really know what is it about, so I will explain it briefly. Besides how remotes are named (which I agree that it would be best if it's configurable), enabling the triangular workflow means:

* If you do a `git push` then you push to your fork instead of to the blessed repo.
* If you do a `git pull` you pull from the blessed repo, not your fork.

This is what you want in a normal GitHub workflow. All the rest are remote names, which should be configurable (I will check now, because there is some support to chose remote names but I think it's not complete).

**Comment by leandro-lucarella-sociomantic** [comment]
It actually doesn't make much sense, the repo that you initially clone is called by convention `origin` in git, and you can override it when clonning with `git clone` (or `git hub clone`) `--origin REMOTE_NAME`. I don't think `git-hub` should mess with this. If you want to use the triangular workflow, you just make it your defaults and your remotes will be named as before.

I really don't see a reasonable way around this. I think new users should get the triangular workflow by default because is the safest and sanest default. I don't think we should doom future generations from our past mistakes :)

Once more, as long as you stick to `git config --global hub.triangular false` and/or always use your remotes explicitly, you should be fine.

As an extra safety measure what I can do is to emit a warning in the next versions before v1.0 if you didn't set `hub.triangular` explicitly, so you get a chance to do so before git-hub changes the behaviour.

**Comment by mihails-strasuns-sociomantic** [comment]
> it configures git to never push to the blessed repo implicitly

See, here is the basic fundamental disagreement we have. You believe that _implicitly_ pushing to _any_ repo can be considered safe and good practice under certain cases in which cases triangular has certain merits. I don't. Actually good thing about current discussion is that I went and finally configured `push.default = nothing` which I should have done ages ago.

With implicit push being prohibited, triangular workflow brings no improvements to the table at all. And the fact that you rename remotes under a premise that upstream is somehow more "origina" (extremely questionable statement on its own) makes it a clear degradation of safety of my workflow.

`git config --global hub.triangular false ` doesn't help much because it is configuration which is very easy to forget on a fresh install (including docker images and virtual machines which I do a lot) and possible consequences from `git push -f origin` become drastic. If this PR goes, I will simply fork and patch git-hub to be honest as that will be much safer in the long run.

**Comment by leandro-lucarella-sociomantic** [comment]
> You believe that implicitly pushing to any repo can be considered safe and good practice under certain cases in which cases triangular has certain merits.

Exactly. I've been using them for ages now and never had an issue with them. It's proven to be safe in my case, I'm not just guessing.

>  I don't.

Perfect.

> And the fact that you rename remotes under a premise that upstream is somehow more "origin" (extremely questionable statement on its own) makes it a clear degradation of safety of my workflow.
> 
> git config --global hub.triangular false doesn't help much because it is configuration which is very easy to forget on a fresh install (including docker images and virtual machines which I do a lot) and possible consequences from git push -f origin become drastic. If this PR goes, I will simply fork and patch git-hub to be honest as that will be much safer in the long run.

OK, I see your concern, you can safely get an error always as long as you never use `origin` and always rename your blessed remote to something like `upstream`.

Again, I do understand your concerns, but this is like https://xkcd.com/1172/, this app misbehaved in the past, I understand you based all your workflow in this behaviour, but I think at some point we need to fix it.

I can consider naming always the blessed repo `upstream` and the fork `fork`, maybe that would help to get consistency, but I think I tried that in the past and it was complicated. If you think that is a good trade-off I could try it again.

**Comment by mihails-strasuns-sociomantic** [comment]
> I can consider naming always the blessed repo upstream and the fork fork, maybe that would help to get consistency, but I think I tried that in the past and it was complicated. If you think that is a good trade-off I could try it again.

That will at least shut me up ;)

**Comment by leandro-lucarella-sociomantic** [comment]
OK, updated. I'm happy with the outcome actually, it seems like it was hard for me to realize how messy the situation with remote names and `--(no-)trianguar` was. I think the new approach is much more consistent. I hope this ends the controversy...

**Comment by leandro-lucarella-sociomantic** [comment]
I will copy the last commit message here to give more context on the final solution:

```
Use consistent names for upstream and fork

Historically the names of the remotes of the upstream repo and fork changed
based on the use of --triangular, because for the originally cloned repo
`origin` was always used as the remote name.

With the change to enable --triangular by default, users pushing explicitly
to origin that are used to origin being the fork (which is how it works
when --no-triangular is used) could get nasty surprises by now finding
themselves pushing to upstream instead.

To avoid this, the remotes are now named consistently, no matter if
--triangular was used or not. By default upstream will always be named
upstream and fork will be named fork, so at least the safe intersection of
both can still be used. Changing the variable name will also avoid
accidental pushes as pushing to origin will be an error unless further
configuration was performed.

For people wanting to stick with --no-triangular by default and want to get
the old naming of remotes, is enough to do:

  git config --global hub.triangular false
  git config --global hub.forkremote origin

For the people that want to use the new --triangular default but want to
get the old naming of remotes, is enough to do:

  git config --global hub.upstreamremote origin

Also new command-line options to change this when git-hub clon'ing are
added: -U/--upstreamremote and -F/--forkremote and the old -r/--remote
option was removed because its meaning depended also on --triangular, which
is confusing and error prone.
```

**Comment by mihails-strasuns-sociomantic** [comment]
Thank you, this is MUCH better. Will give it some testing next week and merge after.

**Comment by leandro-lucarella-sociomantic** [comment]
Ping!

**Comment by mihails-strasuns-sociomantic** [comment]
Tested, works as expected :)

**Pull request merged**
