### PR TITLE
Replace tabs with spaces

### PR DESCRIPTION
**Pull request by gkotian**
A small step towards PEP8.

### CODE REVIEW

**Comment by gkotian** [comment]
I believe everything should _just work_, as all I did was `:% s/^I/    /g` in vim. I haven't obviously verified that every single command works as expected.

FWIW, I made this pull request using the modified `git-hub`.

**Comment by llucax** [comment]
What do you think about adding an [editorconfig](http://editorconfig.org/) file too?

**Comment by llucax** [comment]
Also please mention #98 in the commit message. And if you plan to keep advancing towards PEP8, bear in mind that there are some things that I think really suck about it and not extremely wiling to go full PEP8 (see https://github.com/sociomantic-tsunami/git-hub/pull/125#issuecomment-76389662 for some examples).

**Comment by gkotian** [comment]
Updated with:
- modify commit message to mention #98
- add commit to remove trailing whitespace
- add commit to add a .editorconfig file

>And if you plan to keep advancing towards PEP8, bear in mind that there are some things that I think really suck about it and not extremely wiling to go full PEP8 (see #125 (comment) for some examples).

For now, I have no intention of making major advances towards PEP8, but if that changes, I'll be sure to keep that in mind.

**Comment by leandro-lucarella-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was cf0ba6ed3cd6cc76a6b3b6fb417bfb8d6ae14d16, new (rebased) HEAD is b1e07f75dca2d40259cd868a809cb29ec9c5a3f3

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks!

**Pull request closed without merging**
